replicaCount: 1
image:
  tag: registry-internal-nexus.apps.tssc.rht-set.com/ploigos-ref/ref-spring-jkube-jenkins-typ/hello@sha256:0df0379b26e27e7a44139c467833799ef6f289d47617d87bb6f35c36c08f44d4 # written by ploigos-step-runner
