replicaCount: 1
image:
  tag: registry-internal-nexus.apps.tssc.rht-set.com/ploigos-ref/ref-spring-jkube-jenkins-typ/hello@sha256:f0f756cf58d463908d16068d2df0c16b6e3fcc1c914a48545cd31cf29567feb0 # written by ploigos-step-runner
